"""empty message

Revision ID: 638f2b79d01e
Revises: dc031263e09e
Create Date: 2025-03-22 23:46:07.231593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638f2b79d01e'
down_revision = 'dc031263e09e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
