"""Added head quarters column

Revision ID: dc031263e09e
Revises: c87d2450ddbb
Create Date: 2025-03-20 02:17:57.316640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc031263e09e'
down_revision = 'c87d2450ddbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('head_quarters', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('head_quarters')

    # ### end Alembic commands ###
